# =========================================
# NEW ARCH (required by react-native-worklets / Vision Camera)
# =========================================
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
use_frameworks! :linkage => :static

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] }
    )',
   __dir__]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# =========================================
# FRAMEWORK LINKAGE (OPTIONAL)
# =========================================
linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pods with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# =========================================
# PERMISSIONS
# =========================================
permissions_path = '../node_modules/react-native-permissions/ios'

def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    ['-p',
     "require.resolve(
        '#{script}',
        { paths: [process.argv[1]] }
      )",
     __dir__]
  ).strip
end

node_require('react-native-permissions/scripts/setup.rb')

setup_permissions([
  'Notifications',
  'Camera',
  'LocationWhenInUse'
])

# =========================================
# MAIN TARGET
# =========================================
target 'MemberBaseApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",

    # New Arch + Fabric (required by react-native-worklets)
    :fabric_enabled => true,
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )

    # =====================================
    # EXTRA SAFETY FOR SIMULATOR + ARM
    # =====================================
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      end
    end
  end
end
