/**
 * Component Loader Paths Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npm run generate:loaders
 * 
 * This file is auto-generated from plugin manifests.
 * To regenerate, run: npm run generate:loaders
 * 
 * For manual edits or more details, see: PLUGIN_LOADERS.md
 */

export const COMPONENT_LOADER_PATHS: Record<string, Record<string, string>> = {
  balance: {
    TransactionHistoryScreen: '../../../plugins/balance/components/TransactionHistoryScreen',
    WithdrawIcon: '../../../plugins/balance/components/WithdrawIcon',
    TopUpIcon: '../../../plugins/balance/components/TopUpIcon',
    BalanceCard: '../../../plugins/balance/components/BalanceCard',
  },
  payment: {
    TopUpScreen: '../../../plugins/payment/components/topup/TopUpScreen',
    VirtualAccountScreen: '../../../plugins/payment/components/virtual-account/VirtualAccountScreen',
    WithdrawScreen: '../../../plugins/payment/components/withdraw/WithdrawScreen',
    WithdrawSuccessScreen: '../../../plugins/payment/components/withdraw/WithdrawSuccessScreen',
    TopUpMemberScreen: '../../../plugins/payment/components/topup/TopUpMemberScreen',
    TopUpMemberSummaryScreen: '../../../plugins/payment/components/topup/TopUpMemberSummaryScreen',
    TopUpMemberPinScreen: '../../../plugins/payment/components/topup/TopUpMemberPinScreen',
    TopUpMemberSuccessScreen: '../../../plugins/payment/components/topup/TopUpMemberSuccessScreen',
    TapKartuSummaryScreen: '../../../plugins/payment/components/topup/TapKartuSummaryScreen',
    QrScreen: '../../../plugins/payment/components/qr/QrScreen',
    EditQuickAmountScreen: '../../../plugins/payment/components/qr/EditQuickAmountScreen',
    PinInput: '../../../plugins/payment/components/shared/PinInput',
    WithdrawConfirmModal: '../../../plugins/payment/components/withdraw/WithdrawConfirmModal',
    AutoWithdrawModal: '../../../plugins/payment/components/withdraw/AutoWithdrawModal',
  },
};