/**
 * Component Loader Paths Configuration
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npm run generate:loaders
 * 
 * This file is auto-generated from plugin manifests.
 * To regenerate, run: npm run generate:loaders
 * 
 * For manual edits or more details, see: PLUGIN_LOADERS.md
 */

export const COMPONENT_LOADER_PATHS: Record<string, Record<string, string>> = {
  balance: {
    BalanceDetailScreen: '../../../plugins/balance/components/screens/BalanceDetailScreen',
    TransactionHistoryScreen: '../../../plugins/balance/components/screens/TransactionHistoryScreen',
  },
  marketplace: {
    ProductCard: '../../../plugins/marketplace/components/shared/ProductCard',
    ProductCardSkeleton: '../../../plugins/marketplace/components/shared/ProductCardSkeleton',
    CartBar: '../../../plugins/marketplace/components/shared/CartBar',
    MarketplaceScreen: '../../../plugins/marketplace/components/screens/MarketplaceScreen',
    SearchScreen: '../../../plugins/marketplace/components/screens/SearchScreen',
    SearchResultsScreen: '../../../plugins/marketplace/components/screens/SearchResultsScreen',
    CartScreen: '../../../plugins/marketplace/components/screens/CartScreen',
    ProductDetailScreen: '../../../plugins/marketplace/components/screens/ProductDetailScreen',
    StoreDetailScreen: '../../../plugins/marketplace/components/screens/StoreDetailScreen',
    CheckoutScreen: '../../../plugins/marketplace/components/screens/CheckoutScreen',
  },
  marketplace-fnb: {
    FnBItemCard: '../../../plugins/marketplace-fnb/components/shared/FnBItemCard',
    FnBCategoryTabs: '../../../plugins/marketplace-fnb/components/shared/FnBCategoryTabs',
    FnBCartBar: '../../../plugins/marketplace-fnb/components/shared/FnBCartBar',
    FnBItemDetailSheet: '../../../plugins/marketplace-fnb/components/shared/FnBItemDetailSheet',
    MerchantHeader: '../../../plugins/marketplace-fnb/components/shared/MerchantHeader',
    FnBScreen: '../../../plugins/marketplace-fnb/components/screens/FnBScreen',
    FnBMerchantDetailScreen: '../../../plugins/marketplace-fnb/components/screens/FnBMerchantDetailScreen',
    FnBCheckoutScreen: '../../../plugins/marketplace-fnb/components/screens/FnBCheckoutScreen',
    FnBScanScreen: '../../../plugins/marketplace-fnb/components/screens/FnBScanScreen',
    FnBFavoritesScreen: '../../../plugins/marketplace-fnb/components/screens/FnBFavoritesScreen',
  },
  payment: {
    TopUpScreen: '../../../plugins/payment/components/topup/TopUpScreen',
    VirtualAccountScreen: '../../../plugins/payment/components/virtual-account/VirtualAccountScreen',
    WithdrawScreen: '../../../plugins/payment/components/withdraw/WithdrawScreen',
    WithdrawSuccessScreen: '../../../plugins/payment/components/withdraw/WithdrawSuccessScreen',
    TopUpMemberScreen: '../../../plugins/payment/components/topup/TopUpMemberScreen',
    TopUpMemberSummaryScreen: '../../../plugins/payment/components/topup/TopUpMemberSummaryScreen',
    TopUpMemberPinScreen: '../../../plugins/payment/components/topup/TopUpMemberPinScreen',
    TopUpMemberSuccessScreen: '../../../plugins/payment/components/topup/TopUpMemberSuccessScreen',
    TapKartuSummaryScreen: '../../../plugins/payment/components/topup/TapKartuSummaryScreen',
    PinInput: '../../../plugins/payment/components/shared/PinInput',
    WithdrawConfirmModal: '../../../plugins/payment/components/withdraw/WithdrawConfirmModal',
    AutoWithdrawModal: '../../../plugins/payment/components/withdraw/AutoWithdrawModal',
  },
};